#!/usr/bin/env node
// Generates the repository's images from the measured data.
//
// A picture in a README is a claim like any other. Both artifacts here are
// computed from bench/manifest.json, so the card cannot show a percentage that
// is not in the raw runs, and `--check` fails CI if either file drifts from the
// data. Before the first study lands the manifest is empty and both artifacts
// render in "pre-measurement" form, with no numbers at all - which is the point.
//
//   node scripts/build-assets.mjs           # write assets/*
//   node scripts/build-assets.mjs --check   # exit 1 if a committed asset is stale
//   node scripts/build-assets.mjs --png     # also rasterise the card via headless Chrome
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
// The README results block moved to scripts/build-charts.mjs, which reads the same data
// and writes both languages from one code path. Two generators owning one block meant the
// second one to run silently reverted the first - it happened once, to a good block.

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const MANIFEST = join(REPO, "bench", "manifest.json");
const HEADLINE = join(REPO, "bench", "headline.json");
const ASSETS = join(REPO, "assets");
const CARD_HTML = join(ASSETS, "social-preview.html");
const CARD_PNG = join(ASSETS, "social-preview.png");

const CHROME_CANDIDATES = [
  "C:/Program Files/Google/Chrome/Application/chrome.exe",
  "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe",
  "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
  "/usr/bin/google-chrome",
  "/usr/bin/chromium",
];

const mean = (xs) => (xs.length ? xs.reduce((a, b) => a + b, 0) / xs.length : NaN);
const esc = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

/** Group published runs into { model -> { arm -> [outputTokens] } } plus grading counts. */
export function readData() {
  if (!existsSync(MANIFEST)) return { runs: 0, models: [] };
  const manifest = JSON.parse(readFileSync(MANIFEST, "utf8").replace(/^\ufeff/, ""));
  const allRows = Object.entries(manifest.runs ?? {}).map(([id, r]) => ({ id, ...r }));
  if (!allRows.length) return { runs: 0, models: [] };

  // Everything in bench/raw is published; only the studies listed in
  // bench/headline.json may drive the README table. One batch is not a headline:
  // the same configuration measured -49% in one batch and +24% in another.
  const headline = existsSync(HEADLINE) ? JSON.parse(readFileSync(HEADLINE, "utf8")) : { studies: [] };
  const allowed = new Set(headline.studies ?? []);
  const rows = allRows.filter((r) => allowed.has(r.study));

  const byModel = new Map();
  for (const r of rows) {
    if (!r.model || r.outputTokens == null) continue;
    if (r.arm !== "baseline" && r.arm !== "skill") continue;
    if (!byModel.has(r.model)) byModel.set(r.model, { model: r.model, arms: new Map() });
    const entry = byModel.get(r.model);
    const arm = r.arm === "baseline" ? "baseline" : "eco";
    if (!entry.arms.has(arm)) entry.arms.set(arm, []);
    entry.arms.get(arm).push(r.outputTokens);
  }

  const models = [];
  for (const { model, arms } of byModel.values()) {
    const base = arms.get("baseline") ?? [];
    const eco = arms.get("eco") ?? [];
    if (!base.length || !eco.length) continue;
    const b = mean(base);
    const e = mean(eco);
    models.push({ model, baseline: b, eco: e, n: Math.min(base.length, eco.length), delta: ((e - b) / b) * 100 });
  }
  models.sort((a, b) => a.delta - b.delta);
  return { runs: allRows.length, headlineRuns: rows.length, models };
}


// ------------------------------------------------------------------- the card

export function renderCard(data) {
  const headline = data.models.length
    ? `&minus;${Math.abs(data.models[0].delta).toFixed(0)}% output tokens`
    : "Measured, or not claimed";
  const sub = data.models.length
    ? `${data.models[0].model} &middot; same review task &middot; n=${data.models[0].n} per arm &middot; both planted bugs found`
    : "The mechanism is built and verified. The percentages wait for the study.";
  const proof = data.models.length
    ? `<b>${data.runs} raw runs</b> published, negative results included<br>every number recomputed from them <b>in CI</b>`
    : `<b>0 raw runs</b> published so far<br>this card refuses to show a number nobody measured`;

  return `<!DOCTYPE html>
<!-- Social preview card, generated by scripts/build-assets.mjs from bench/manifest.json.
     Do not edit by hand: run the generator. Render at 1280x640. -->
<html lang="en">
<head>
<meta charset="utf-8">
<title>codex-eco social preview</title>
<style>
  :root {
    --bg: #080b11; --bg2: #0e1420; --panel: #0c1320; --line: #1c2740;
    --ink: #e8ecf3; --dim: #8e99ac; --green: #34d399; --green-dim: #1c7a5a;
    --red: #f87171; --amber: #fbbf24;
  }
  * { box-sizing: border-box; }
  body { margin: 0; background: #05070b; font-family: "Segoe UI", -apple-system, BlinkMacSystemFont, sans-serif; }
  .card {
    width: 1280px; height: 640px; padding: 46px 56px 40px;
    background:
      radial-gradient(1100px 520px at 88% -12%, rgba(52, 211, 153, 0.13), transparent 62%),
      linear-gradient(140deg, var(--bg) 0%, var(--bg2) 100%);
    color: var(--ink); display: flex; flex-direction: column; position: relative; overflow: hidden;
  }
  .card::before {
    content: ""; position: absolute; inset: 0; pointer-events: none;
    background-image: linear-gradient(rgba(255,255,255,.028) 1px, transparent 1px),
                      linear-gradient(90deg, rgba(255,255,255,.028) 1px, transparent 1px);
    background-size: 64px 64px;
    mask-image: linear-gradient(180deg, rgba(0,0,0,.9), transparent 78%);
  }
  header { display: flex; align-items: flex-start; justify-content: space-between; z-index: 1; }
  .brand { font-size: 46px; font-weight: 800; letter-spacing: -1.4px; line-height: 1; }
  .brand .eco { color: var(--green); }
  .tag { font-size: 21px; color: var(--dim); margin-top: 10px; letter-spacing: -.2px; }
  .chip {
    font-size: 15px; font-weight: 700; color: var(--green); letter-spacing: .3px;
    border: 1px solid var(--green-dim); border-radius: 999px; padding: 7px 14px;
    background: rgba(52, 211, 153, .08); white-space: nowrap;
  }
  .levers { display: flex; gap: 14px; margin-top: 32px; z-index: 1; }
  .lever {
    flex: 1; background: var(--panel); border: 1px solid var(--line); border-radius: 13px; padding: 16px 18px;
  }
  .lever h3 {
    margin: 0 0 8px; font-size: 12.5px; font-weight: 700; letter-spacing: .7px; text-transform: uppercase; color: var(--green);
  }
  .lever code {
    display: block; font-family: "Cascadia Mono", Consolas, ui-monospace, monospace; font-size: 13.5px;
    color: var(--ink); line-height: 1.55;
  }
  .lever span { display: block; margin-top: 8px; font-size: 13px; color: var(--dim); line-height: 1.45; }
  .surfaces { display: flex; gap: 10px; margin-top: 20px; z-index: 1; font-size: 14.5px; color: var(--dim); }
  .surfaces b { color: var(--ink); font-weight: 600; }
  .install {
    margin-top: 20px; z-index: 1; background: rgba(52, 211, 153, .05); border: 1px solid var(--green-dim);
    border-radius: 13px; padding: 16px 20px; display: flex; gap: 34px; align-items: center;
  }
  .install .col h4 {
    margin: 0 0 7px; font-size: 12px; font-weight: 700; letter-spacing: .7px; text-transform: uppercase; color: var(--dim);
  }
  .install code {
    font-family: "Cascadia Mono", Consolas, ui-monospace, monospace; font-size: 14px; color: var(--ink);
    display: block; line-height: 1.6; white-space: nowrap;
  }
  .install .sep { width: 1px; align-self: stretch; background: var(--line); }
  footer { margin-top: auto; padding-top: 18px; display: flex; align-items: flex-end; justify-content: space-between; gap: 40px; z-index: 1; }
  .headline { font-size: 40px; font-weight: 800; color: var(--green); letter-spacing: -1px; line-height: 1.05; }
  .headline small { display: block; font-size: 17px; font-weight: 500; color: var(--dim); letter-spacing: -.2px; margin-top: 8px; }
  .proof { text-align: right; font-size: 15px; color: var(--dim); line-height: 1.7; padding-bottom: 2px; }
  .proof b { color: var(--ink); font-weight: 600; }
</style>
</head>
<body>
<div class="card">
  <header>
    <div>
      <div class="brand">codex-<span class="eco">eco</span></div>
      <div class="tag">Eco mode for Codex &mdash; fewer tokens per turn, with a correctness floor that is measured.</div>
    </div>
    <div class="chip">CLI &middot; ChatGPT desktop app</div>
  </header>

  <div class="levers">
    <div class="lever">
      <h3>Turns the real knobs</h3>
      <code>model_reasoning_effort<br>model_verbosity<br>model_reasoning_summary<br>tool_output_token_limit</code>
      <span>Six config levers, not just prose the model may ignore.</span>
    </div>
    <div class="lever">
      <h3>Deletes measured waste</h3>
      <code>no preamble turn<br>no unasked survey<br>region reads, not dumps<br>apply_patch, not rewrites</code>
      <span>Each rule targets something observed in a real Codex transcript.</span>
    </div>
    <div class="lever">
      <h3>Keeps itself honest</h3>
      <code>deterministic grader<br>provenance manifest<br>pre-registered studies<br>every claim re-derived in CI</code>
      <span>Ported from a sibling project with 267 published runs.</span>
    </div>
  </div>

  <div class="surfaces">
    <div><b>$eco</b> in the CLI &nbsp;&middot;&nbsp; <b>@eco</b> in the desktop app &nbsp;&middot;&nbsp; one install for both</div>
  </div>

  <div class="install">
    <div class="col">
      <h4>Install (CLI + desktop app)</h4>
      <code>git clone https://github.com/sup3x/codex-eco</code>
      <code>cd codex-eco &amp;&amp; ./install.sh</code>
    </div>
    <div class="sep"></div>
    <div class="col">
      <h4>Or as a Codex plugin</h4>
      <code>codex plugin marketplace add sup3x/codex-eco</code>
      <code>codex plugin add eco@codex-eco</code>
    </div>
  </div>

  <footer>
    <div class="headline">${headline}
      <small>${sub}</small>
    </div>
    <div class="proof">${proof}</div>
  </footer>
</div>
</body>
</html>
`;
}

// ----------------------------------------------------------------- the driver

function findChrome() {
  for (const c of CHROME_CANDIDATES) if (existsSync(c)) return c;
  return null;
}

function rasterise() {
  const chrome = findChrome();
  if (!chrome) {
    console.log("skipped PNG: no Chrome/Chromium found - the HTML card is still generated");
    return false;
  }
  execFileSync(
    chrome,
    [
      "--headless",
      "--disable-gpu",
      "--hide-scrollbars",
      "--force-device-scale-factor=1",
      "--window-size=1280,640",
      `--screenshot=${CARD_PNG}`,
      pathToFileURL(CARD_HTML).href,
    ],
    { stdio: "ignore" },
  );
  console.log(`wrote ${CARD_PNG}`);
  return true;
}

function main() {
  const check = process.argv.includes("--check");
  const png = process.argv.includes("--png");
  const data = readData();
  // assets/models.svg is generated by scripts/build-charts.mjs, together with every other
  // chart and both languages. This script owns the social card only.
  const artifacts = [{ file: CARD_HTML, content: renderCard(data) }];

  if (check) {
    let stale = 0;
    for (const a of artifacts) {
      const current = existsSync(a.file) ? readFileSync(a.file, "utf8") : "";
      if (current.replace(/\r\n/g, "\n") !== a.content) {
        console.error(`stale: ${a.file} does not match bench/manifest.json`);
        stale++;
      }
    }
    if (stale) {
      console.error("run `node scripts/build-assets.mjs` and commit the result.");
      return 1;
    }
    console.log(`ok: assets match the data (${data.runs} published runs, ${data.models.length} model rows)`);
    return 0;
  }

  mkdirSync(ASSETS, { recursive: true });
  for (const a of artifacts) {
    writeFileSync(a.file, a.content, "utf8");
    console.log(`wrote ${a.file} (${a.content.length} bytes)`);
  }
  if (png) rasterise();
  console.log(`data: ${data.runs} published runs, ${data.models.length} model rows`);
  return 0;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  try {
    process.exit(main());
  } catch (err) {
    console.error(`error: ${err.message}`);
    process.exit(2);
  }
}
