#!/usr/bin/env node
// Record a prefix audit as a dated snapshot, so a chart can be built from it in CI.
//
// The audit itself needs the Codex CLI, which CI does not have. Rather than let the
// chart carry numbers with no source, the audit is run on a real machine, written here
// with the provenance that makes it checkable - Codex version, model, prompt, the
// per-section breakdown - and the chart generator reads only this file.
//
// Re-run it when Codex changes:  node scripts/snapshot-prefix.mjs
import { execFileSync } from "node:child_process";
import { writeFileSync, mkdirSync } from "node:fs";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { renderPrompt, catalogue, duplicateSkills } from "../bench/lib/preflight.mjs";

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(REPO, "assets", "data", "prefix.json");

function main() {
  const raw = execFileSync(process.execPath, [join(REPO, "scripts", "prefix-audit.mjs"), "--json"], {
    encoding: "utf8",
    maxBuffer: 64 * 1024 * 1024,
    stdio: ["ignore", "pipe", "inherit"],
  });
  const audit = JSON.parse(raw);
  const version = execFileSync("codex", ["--version"], { encoding: "utf8" }).trim();

  // Skills installed on the machine that ran this inflate the catalogue, and the
  // catalogue is the largest section, so the total is meaningless without the count.
  const rendered = renderPrompt({ cwd: REPO, prompt: audit.prompt });
  const rows = rendered ? catalogue(rendered) : [];
  const dupes = duplicateSkills(rows);

  const snapshot = {
    $comment:
      "Generated by scripts/snapshot-prefix.mjs from a real `codex debug prompt-input` render. " +
      "assets/prefix.svg is built from this file and nothing else. Character counts, not tokens: " +
      "the ~tokens column in the audit is chars/4, an estimate, and the chart says so.",
    recordedAt: new Date().toISOString().slice(0, 10),
    codexVersion: version,
    model: audit.model,
    prompt: audit.prompt,
    skillsInCatalogue: rows.length,
    duplicateSkillNames: dupes.map((d) => d.name),
    baseline: { total: audit.baseline.total, sections: audit.baseline.sections },
    tiers: audit.tiers.map((t) => ({ id: t.id, total: t.total, delta: t.delta, pct: t.pct, sections: t.sections })),
  };
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, `${JSON.stringify(snapshot, null, 2)}\n`, "utf8");
  console.log(
    `wrote ${OUT}\n  ${version} | baseline ${snapshot.baseline.total} chars | ` +
      snapshot.tiers.map((t) => `${t.id} ${t.total} (${t.pct.toFixed(1)}%)`).join(" | ") +
      `\n  ${rows.length} skills in the catalogue` +
      (dupes.length ? `, and ${dupes.length} name(s) published twice: ${dupes.map((d) => d.name).join(", ")}` : ""),
  );
  return 0;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  try {
    process.exit(main());
  } catch (err) {
    console.error(`error: ${err.message}`);
    process.exit(2);
  }
}
